### ISSUE TITLE
Text of test result is exceeding the cell margin

### ISSUE THREAD

**Issue by nuummi** [tungwaiyip/HTMLTestRunner#2]
Hi,
in version 0.8.2, a long text of the test result is exceeding the cell margin,
once I click on the fail/pass/error hyperlink to view the result.

Any workaround ?

Thanks!
Noam.

**Comment by tungwaiyip** [comment]
The formatting need to improve a bit.

A quick workaround is the change the CSS from

```
pre         {}

to

pre         { white-space: pre-wrap; }
```

**Comment by nuummi** [comment]
Thanks! 
I changed it to 
{ white-space: pre-wrap; word-wrap:break-word}

So it will also warp long text with no spaces (like a long filepath).
