### ISSUE TITLE
expand collapse button for traceback in error log window

### ISSUE THREAD

**Issue by vnitinv** [tungwaiyip/HTMLTestRunner#3]
I am using your html runner for generating report. 
But from user there is one request that in fail case the traceback should be expandable.
Meaning, if we want to see traceback then there should be button (say named traceback) which will expand to see the detail.
We need this because traceback in log make log very messy.

Please tell me how to achieve this or what all changes i need to do in HTMLRunner.py?

**Comment by vnitinv** [comment]
I got it done after doing some syntex change

Thanks

**Comment by Kingson** [comment]
@vnitinv How do you solve it?

**Comment by vnitinv** [comment]
@Kingson I dont have the code right now. Will search for it and share with you. (infact will send a pull request). What I remember i had changed HTML syntax to handle that.

**Comment by Kingson** [comment]
Hi @vnitinv 
Thank you for replay me. Can you share with me that you fixed  the code?

**Comment by seven-santhosh** [comment]
@Kingson i have attached the snippet of the code that we did for this fix.
we modified REPORT_TEST_WITH_OUTPUT_TMPL
and added new template for tracelog (REPORT_TEST_OUTPUT_TMPL_TRACE) you can see this in the following snippet..
![image](https://cloud.githubusercontent.com/assets/6582098/4899423/d5d28b84-641b-11e4-80e3-dc7eb917147e.png)

these templates were used in this modified function _generate_report_test().
![image](https://cloud.githubusercontent.com/assets/6582098/4899484/88ce5272-641c-11e4-9930-050b1982ab58.png)

I hope this serves your requirement..
