### ISSUE TITLE
Storing HtmlTestRunner reports in Web Server

### ISSUE THREAD

**Issue by nuummi** [tungwaiyip/HTMLTestRunner#4]
Hi,
Can you recommend of a good way to store HtmlTestRunner reports in a Web Server with Database ?

Can I use Django for that purpose, so that the unit test results be stored in database, and Django will use HtmlTestRunner Template ?

Thanks!

**Comment by tungwaiyip** [comment]
The report is just a text string. The simplest way is to store them in a text file encoded with the timestamp. E.g.

"2011-09-06 test report.html"

**Comment by nuummi** [comment]
I meant to store the HTML content inside DB, not the HTML file name...

**Comment by tungwaiyip** [comment]
You can simply create a table with a date and a text field. The text is HTML. So it can be served directly without using template. Details of using Django is outside the scope of this tool.
